### ISSUE TITLE
Outliers sometimes trigger divide-by-zero

### ISSUE THREAD

**Issue by zane** [probcomp/curve-fitting#30]
## Reproduction steps
1. Change the `:sketch-type` to `:resampling` in `system.clj`.
2. Launch a REPL with `make dev`.
3. Start the visualization with `(go)`.
4. Click to place four points in a line with one clear outlier as in the following image.

![curve-fitting visualization](https://user-images.githubusercontent.com/26162/48985278-d9582b80-f0d3-11e8-8b61-80f11602d9ae.png)

## Expected results
The visualization continuously samples and displays traces.

## Actual results
The sampling threads die with the following exception:

```
java.lang.ArithmeticException: Divide by zero
	at clojure.lang.Numbers.divide(Numbers.java:163)
	at clojure.core$_SLASH_.invokeStatic(core.clj:1019)
	at clojure.core$_SLASH_.invoke(core.clj:1012)
	at metaprob.distributions$scores_to_probabilities__9519$fn__9520.invoke(distributions.clj:126)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at metaprob.builtin_impl$generate_foreign.invokeStatic(builtin_impl.clj:60)
	at metaprob.builtin_impl$generate_foreign.invoke(builtin_impl.clj:58)
	at metaprob.builtin_impl$infer_apply.invokeStatic(builtin_impl.clj:288)
	at metaprob.builtin_impl$infer_apply.invoke(builtin_impl.clj:281)
	at metaprob.prelude$fn__9358$re__9362.invoke(prelude.clj:192)
	at metaprob.prelude$fn__9358.invokeStatic(prelude.clj:213)
	at metaprob.prelude$fn__9358.invoke(prelude.clj:187)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metaprob.builtin_impl$inf$fn__9106.doInvoke(builtin_impl.clj:268)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metaprob.distributions$scores_to_probabilities__9519.invokeStatic(distributions.clj:126)
	at metaprob.distributions$scores_to_probabilities__9519.invoke(distributions.clj:121)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metaprob.distributions$fn__9507.invokeStatic(distributions.clj:110)
	at metaprob.distributions$fn__9507.invoke(distributions.clj:102)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at metaprob.prelude$fn__9355.invokeStatic(prelude.clj:180)
	at metaprob.prelude$fn__9355.invoke(prelude.clj:179)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metaprob.distributions$make_inference_procedure_from_sampler_and_scorer__9471$fn__9472.invoke(distributions.clj:23)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metaprob.builtin_impl$inf$fn__9106.doInvoke(builtin_impl.clj:268)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at curve_fitting.inference$importance_resampling__17085.invokeStatic(inference.clj:35)
	at curve_fitting.inference$importance_resampling__17085.invoke(inference.clj:17)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at curve_fitting.sketches.resampling$sample_curve.invokeStatic(resampling.clj:11)
	at curve_fitting.sketches.resampling$sample_curve.invoke(resampling.clj:7)
	at curve_fitting.system$eval17384$fn__17386$fn__17391.invoke(system.clj:36)
	at curve_fitting.sketches$sampling_thread$fn__17235.invoke(sketches.clj:38)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alex-lew** [comment]
Should be fixed by https://github.com/probcomp/metaprob/pull/99 in the Metaprob repo.
